name: Deploy with Docker

on:
  workflow_dispatch:

jobs:
  notify:
    name: Notify Slack
    uses: strongmind/public-reusable-workflows/.github/workflows/notify-slack.yml@BEL-789
    secrets: inherit
